version: "3.8"

services:
    verdad:
        container_name: verdad_backend
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        environment:
            - PREFECT_API_URL=http://prefect:4200/api
        depends_on:
            - prefect
        volumes:
            - verdad_data:/root/.verdad

    prefect:
        container_name: prefect_server
        build:
            context: .
            dockerfile: Dockerfile.prefect
        ports:
            - "4200:4200"
        environment:
            - PREFECT_SERVER_API_HOST=0.0.0.0
            - PREFECT_SERVER_API_PORT=4200
        volumes:
            - prefect_data:/root/.prefect

volumes:
    verdad_data:
    prefect_data:
