app = "verdad-dev"
primary_region = "sea"

[build]
  dockerfile = "Dockerfile.dev"

[env]
  PREFECT_API_URL = "https://prefect-staging.fly.dev/api"

[[processes]]
  name = "radio_vov1"

[[processes]]
  name = "radio_dn_rtv"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[scale]
  radio_vov1 = 1
  radio_dn_rtv = 1
