app = 'processing-worker'
primary_region = 'sea'

[build]
  dockerfile = 'Dockerfile.processing_worker'

[env]
  PREFECT_API_URL = 'https://prefect.fly.dev/api'

[processes]
  initial_disinformation_detection = ''
  audio_clipping = ''
  in_depth_analysis = ''
  rerun_main_detection_phase = ''
  undo_audio_clipping = ''
  undo_in_depth_analysis = ''

[[vm]]
  processes = ["initial_disinformation_detection"]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4

[[vm]]
  processes = ["audio_clipping", "in_depth_analysis"]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 4

[[vm]]
  processes = ["rerun_main_detection_phase"]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[vm]]
  processes = ["undo_audio_clipping", "undo_in_depth_analysis"]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[scale]
  initial_disinformation_detection = 1
  audio_clipping = 1
  in_depth_analysis = 1
  rerun_main_detection_phase = 1
  undo_audio_clipping = 1
  undo_in_depth_analysis = 1
