app = 'generic-recording-worker'
primary_region = 'sea'

[build]
  dockerfile = 'Dockerfile.generic_recording_worker'

[env]
  PREFECT_API_URL = 'https://prefect-staging.fly.dev/api'

[processes]
  radio_k229db = ''
  radio_kfue = ''
  radio_khot = ''
  radio_kisf = ''
  radio_kmma = ''
  radio_krgt = ''
  radio_rumba_4451 = ''
  radio_wbzw = ''
  radio_wbzy = ''
  radio_wrum_hd2 = ''
  radio_wrum = ''
  radio_wumr = ''
  radio_wztu = ''

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[scale]
  radio_k229db = ''
  radio_kfue = ''
  radio_khot = ''
  radio_kisf = 1
  radio_kmma = ''
  radio_krgt = 1
  radio_rumba_4451 = ''
  radio_wbzw = 1
  radio_wbzy = 1
  radio_wrum_hd2 = 1
  radio_wrum = 1
  radio_wumr = 1
  radio_wztu = 1
