app = 'recording-worker'
primary_region = 'sea'

[build]
  dockerfile = "Dockerfile.recording_worker"

[env]
  PREFECT_API_URL = "https://prefect.fly.dev/api"

[processes]
  max_recorder = ''
  lite_recorder = ''

[[vm]]
  processes = ['max_recorder']
  memory = '8gb'
  cpu_kind = 'shared'
  cpus = 8

[[vm]]
  processes = ['lite_recorder']
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4

[scale]
  max_recorder = 1
  lite_recorder = 1
