app = 'generic-recording-worker'
primary_region = 'sea'

[build]
  dockerfile = 'Dockerfile.generic_recording_worker'

[env]
  PREFECT_API_URL = 'https://prefect.fly.dev/api'

[processes]
  radio_khot = ''
  radio_kisf = ''
  radio_krgt = ''

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[scale]
  radio_khot = 1
  radio_kisf = 1
  radio_krgt = 1
