app = 'verdad-dev'
primary_region = 'sea'

[build]
  dockerfile = 'Dockerfile.generic_recording_worker'

[env]
  PREFECT_API_URL = 'https://prefect.fly.dev/api'

[processes]
  radio_khot = ''

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[scale]
  radio_khot = 1
