app = 'processing-worker'
primary_region = 'sea'

[build]
  dockerfile = 'Dockerfile.processing_worker'

[env]
  PREFECT_API_URL = 'https://prefect.fly.dev/api'

[processes]
  initial_disinformation_detection = ''
  audio_clipping = ''
  in_depth_analysis = ''

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 4

[scale]
  initial_disinformation_detection = 1
  audio_clipping = 1
  in_depth_analysis = 1
