app = 'processing-worker'
primary_region = 'sea'

[build]
  dockerfile = 'Dockerfile.processing_worker'

[env]
  PREFECT_API_URL = 'https://prefect.fly.dev/api'

[processes]
  initial_disinformation_detection = ''
  audio_clipping = ''
  in_depth_analysis = ''
  regenerate_timestamped_transcript = ''
  redo_main_detection = ''
  undo_disinformation_detection = ''
  undo_audio_clipping = ''
  embedding = ''

[[vm]]
  processes = ["initial_disinformation_detection"]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 8

  [[vm]]
  processes = ["audio_clipping"]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4

[[vm]]
  processes = ["regenerate_timestamped_transcript", "in_depth_analysis", "embedding"]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 4

[[vm]]
  processes = ["redo_main_detection", "undo_audio_clipping", "undo_disinformation_detection"]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
