app = "prefect"
primary_region = "sea"

[build]
  dockerfile = "Dockerfile.prefect"

[http_service]
  internal_port = 4200
  force_https = true
  auto_stop_machines = true
  min_machines_running = 1

[env]
  PREFECT_SERVER_API_HOST = "0.0.0.0"
  PREFECT_SERVER_API_PORT = "4200"
  PREFECT_API_DATABASE_CONNECTION_URL = "${DATABASE_URL}"

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 4
