import os
import time
import boto3
from prefect.task_runners import ConcurrentTaskRunner
from processing_pipeline.supabase_utils import SupabaseClient
from utils import optional_flow

from processing_pipeline.stage_2.tasks import (
    fetch_a_new_stage_1_llm_response_from_supabase,
    download_audio_file_from_s3,
    process_llm_response,
    fetch_stage_1_llm_response_from_supabase,
    fetch_snippets_from_supabase,
    delete_snippet_from_r2,
    delete_snippet_from_supabase,
    reset_status_of_stage_1_llm_response,
)


@optional_flow(name="Stage 2: Audio Clipping", log_prints=True, task_runner=ConcurrentTaskRunner)
def audio_clipping(context_before_seconds, context_after_seconds, repeat):
    # Setup S3 Client
    R2_BUCKET_NAME = os.getenv("R2_BUCKET_NAME")
    s3_client = boto3.client(
        "s3",
        endpoint_url=os.getenv("R2_ENDPOINT_URL"),
        aws_access_key_id=os.getenv("R2_ACCESS_KEY_ID"),
        aws_secret_access_key=os.getenv("R2_SECRET_ACCESS_KEY"),
    )

    # Setup Supabase client
    supabase_client = SupabaseClient(supabase_url=os.getenv("SUPABASE_URL"), supabase_key=os.getenv("SUPABASE_KEY"))

    while True:
        llm_response = fetch_a_new_stage_1_llm_response_from_supabase(
            supabase_client
        )  # TODO: Retry failed llm responses (Error)

        if llm_response:
            local_file = download_audio_file_from_s3(s3_client, R2_BUCKET_NAME, llm_response["audio_file"]["file_path"])

            # Process the stage-1 LLM response
            process_llm_response(
                supabase_client,
                llm_response,
                local_file,
                s3_client,
                R2_BUCKET_NAME,
                context_before_seconds,
                context_after_seconds,
            )

            print(f"Delete the downloaded audio file: {local_file}")
            os.remove(local_file)

        # Stop the flow if it should not be repeated
        if not repeat:
            break

        if llm_response:
            sleep_time = 2
        else:
            sleep_time = 60

        print(f"Sleep for {sleep_time} seconds before the next iteration")
        time.sleep(sleep_time)


@optional_flow(name="Stage 2: Undo Audio Clipping", log_prints=True, task_runner=ConcurrentTaskRunner)
def undo_audio_clipping(stage_1_llm_response_ids):
    # Setup S3 Client
    R2_BUCKET_NAME = os.getenv("R2_BUCKET_NAME")
    s3_client = boto3.client(
        "s3",
        endpoint_url=os.getenv("R2_ENDPOINT_URL"),
        aws_access_key_id=os.getenv("R2_ACCESS_KEY_ID"),
        aws_secret_access_key=os.getenv("R2_SECRET_ACCESS_KEY"),
    )

    # Setup Supabase client
    supabase_client = SupabaseClient(supabase_url=os.getenv("SUPABASE_URL"), supabase_key=os.getenv("SUPABASE_KEY"))

    for id in stage_1_llm_response_ids:
        stage_1_llm_response = fetch_stage_1_llm_response_from_supabase(supabase_client, id)

        if stage_1_llm_response:
            print(f"Found stage-1 LLM response: {id}")

            # Identify the snippets that were generated by this stage-1 LLM response
            detection_result = stage_1_llm_response["detection_result"] or {}
            flagged_snippets = detection_result.get("flagged_snippets", [])
            snippet_ids = [snippet["uuid"] for snippet in flagged_snippets]
            if len(snippet_ids) > 0:
                print("The following snippets were generated by this stage-1 LLM response:")
                print("\n".join(f" - {snippet_id}" for snippet_id in snippet_ids))

                # Load those snippets from Supabase
                snippets = fetch_snippets_from_supabase(supabase_client, snippet_ids)

                # Handle those snippets:
                # 1. Delete the snippet file from R2
                # 2. Delete the snippet from Supabase
                for snippet in snippets:
                    print(f"Deleting snippet file from R2: {snippet['file_path']}")
                    delete_snippet_from_r2(s3_client, R2_BUCKET_NAME, snippet["file_path"])

                    print(f"Deleting snippet from Supabase: {snippet['id']}")
                    delete_snippet_from_supabase(supabase_client, snippet["id"])
            else:
                print(f"No snippets were generated by this stage-1 LLM response {id}")

            # Reset the stage-1 LLM response status to New, error_message to None
            print(f"Resetting status of stage-1 LLM response: {id}")
            reset_status_of_stage_1_llm_response(supabase_client, id)

            print(f"Complete reverting Stage 2 for snippet {id}")
